### ISSUE TITLE
Returning {"message":"Not Found"} with 404 status code when requesting the apiGwEndpoint.

### ISSUE THREAD

**Issue by 1marcghannam** [aws-samples/aws-graph-blockchain-indexer#11]
Hey guys! I'm successfully running the deployment scripts up to the part where I get the Outputs with the TheGraphServiceStack.apiGwEndpoint and when I try to request the endpoint I get a 404.

**Comment by chrisdotn** [comment]
Hi, it sounds like there might be a problem with the URL you're trying to access. Can you do two things:

1. post the URL you're trying to access as a comment (ideally with the CURL command)
2. try to access this URL (for the status queries of the graph node via curl:

```
curl --request POST \
  --url https://<NODE ID>.execute-api.<REGION>.amazonaws.com/graphql \
  --header 'Content-Type: application/json' \
  --header 'authorization: <AUTH TOKEN>' \
  --data '{"query":"query { indexingStatuses { subgraph synced health fatalError { block { number } message handler } nonFatalErrors { block { number } message handler } chains { network chainHeadBlock { number } earliestBlock { number } latestBlock { number } lastHealthyBlock { number } } entityCount node } }"}'
```

**Note:** Before running above command, please substitute the placeholders:
- `<NODE ID>` with the node ID for the ApiGW
- `<REGION>` with the region the stack is deployed in (if you didn't change it, this defaults to `us-east-1`
- `<AUTH TOKEN>` to authorize you access. If you haven't changed it, the default is `secretToken`.

Can you post the result?

**Comment by chrisdotn** [comment]
closing as stale
